# Generated by Django 5.1.4 on 2025-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
