# Generated by Django 5.1.4 on 2025-01-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_delivery_fecha_and_more'),
        ('user_r', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.IntegerField(default=0)),
                ('banco', models.CharField(max_length=4)),
                ('monto', models.FloatField(default=0)),
                ('ref', models.IntegerField()),
                ('titular', models.CharField(default='', max_length=40)),
                ('telefono', models.CharField(default='', max_length=11)),
                ('id_nro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.IntegerField(default=0)),
                ('banco', models.CharField(max_length=4)),
                ('monto', models.FloatField(default=0)),
                ('ref', models.IntegerField()),
                ('titular', models.CharField(default='', max_length=40)),
                ('telefono', models.CharField(default='', max_length=11)),
                ('id_nro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
        migrations.DeleteModel(
            name='PagoNacional',
        ),
    ]
