# Generated by Django 5.1.4 on 2025-01-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pagoefectivo_banco_remove_pagoefectivo_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_pickup',
            name='ubicacion',
        ),
    ]
