# Generated by Django 5.1.4 on 2025-01-04 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_pickup_ubicacion'),
        ('user_r', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_pickup',
            name='id_nro',
        ),
        migrations.RemoveField(
            model_name='pagoefectivo',
            name='id_nro',
        ),
        migrations.RemoveField(
            model_name='pagomovil',
            name='id_nro',
        ),
        migrations.RemoveField(
            model_name='paypalmodel',
            name='id_nro',
        ),
        migrations.RemoveField(
            model_name='zellemodel',
            name='id_nro',
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('nro_items', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.CharField(max_length=500)),
                ('cantidades', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=11)),
                ('ubicacion', models.CharField(default='No aplica', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('monto', models.FloatField(default=0)),
                ('is_delivery', models.BooleanField(default=0)),
                ('is_pickup', models.BooleanField(default=0)),
                ('nro', models.AutoField(primary_key=True, serialize=False)),
                ('id_nro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
        migrations.AlterField(
            model_name='pagoefectivo',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidomodel'),
        ),
        migrations.AlterField(
            model_name='pagomovil',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidomodel'),
        ),
        migrations.AlterField(
            model_name='paypalmodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidomodel'),
        ),
        migrations.AlterField(
            model_name='zellemodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidomodel'),
        ),
        migrations.DeleteModel(
            name='Pedido_Delivery',
        ),
        migrations.DeleteModel(
            name='Pedido_Pickup',
        ),
    ]
