# Generated by Django 5.1.4 on 2025-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_pedido_pickup_id_nro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomovil',
            name='precio_dolar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paypalmodel',
            name='precio_dolar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zellemodel',
            name='precio_dolar',
            field=models.FloatField(default=0),
        ),
    ]
