# Generated by Django 5.1.4 on 2025-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pagomovil_precio_dolar_paypalmodel_precio_dolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='puntodeventa_active',
            field=models.BooleanField(default=0),
        ),
    ]
