# Generated by Django 5.1.4 on 2025-01-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones_horario',
            name='status',
            field=models.CharField(default='0', max_length=144),
        ),
    ]
