# Generated by Django 5.1.4 on 2025-01-05 22:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_reservaciones_horario_status'),
        ('user_r', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion_cliente',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('nro_reserva', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('identificacion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.date(2025, 1, 5))),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('mesa', models.IntegerField(default=0)),
                ('nro_personas', models.IntegerField(default=0)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
    ]
