# Generated by Django 5.1.4 on 2025-01-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_reservacion_cliente_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion_cliente',
            name='id',
        ),
    ]
