# Generated by Django 5.1.4 on 2025-01-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_reservacion_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion_cliente',
            name='nro_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
