# Generated by Django 5.1.4 on 2025-01-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_reservacion_cliente_nro_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion_cliente',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
