# Generated by Django 5.1.4 on 2024-12-31 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=18)),
                ('rif', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=200)),
                ('fundacion', models.DateField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', models.CharField(default='default_logo.jpg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_active', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('phone_p', models.CharField(default=0, max_length=11)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagomovil_active', models.BooleanField(default=False)),
                ('banco', models.CharField(max_length=4)),
                ('telefono_pm', models.CharField(max_length=11)),
                ('efectivo_active', models.BooleanField(default=False)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('comida', models.TextField(max_length=2750)),
                ('precios', models.TextField(max_length=360)),
                ('codigo', models.CharField(max_length=360)),
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Zelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zelle_active', models.BooleanField(default=False)),
                ('mail_z', models.EmailField(max_length=254)),
                ('phone_z', models.CharField(max_length=11)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_r.restaurante')),
            ],
        ),
    ]
