# Generated by Django 5.1.4 on 2025-01-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0002_remove_restaurante_password_restaurante_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
