# Generated by Django 5.1.4 on 2025-01-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0003_rename_username_restaurante_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
    ]
