# Generated by Django 5.1.4 on 2025-01-09 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0006_rename_usuario_restaurante_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='fundacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
