# Generated by Django 5.1.4 on 2025-01-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0008_pago_punto_active_alter_restaurante_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(default='0+0+20', max_length=50),
        ),
    ]
