# Generated by Django 5.1.4 on 2025-01-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0010_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
    ]
