# Generated by Django 5.1.4 on 2025-01-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0011_alter_cliente_username_alter_restaurante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
    ]
