# Generated by Django 5.1.4 on 2025-01-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0012_alter_cliente_email_alter_restaurante_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='password2',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
