# Generated by Django 5.1.4 on 2025-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0013_remove_restaurante_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(upload_to='static\\img'),
        ),
    ]
