# Generated by Django 5.1.4 on 2025-01-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0014_alter_restaurante_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
