# Generated by Django 5.1.4 on 2025-01-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0015_alter_restaurante_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(null=True, upload_to='restaurantes'),
        ),
    ]
