# Generated by Django 5.1.4 on 2025-01-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_r', '0016_alter_restaurante_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(null=True, upload_to='comida'),
        ),
    ]
